# Site settings
title: "Servo Blog"
description: ""
baseurl: "https://servo.github.io/blog.servo.org/"
url: "http://blog.servo.org"
google_analytics: 

#  Build settings
markdown: kramdown
permalink: pretty
paginate: 3
