# Site settings
title: "Servo Blog"
description: ""
url: "http://blog.servo.org"
google_analytics: 

#  Build settings
markdown: kramdown
permalink: pretty
paginate: 3

gems:
  - jekyll-redirect-from
